// Copyright IstioFilter Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/istio-conductor/istiofilter/client-go/pkg/apis/istiofilter/v1alpha1"
	scheme "github.com/istio-conductor/istiofilter/client-go/pkg/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// IstioFiltersGetter has a method to return a IstioFilterInterface.
// A group's client should implement this interface.
type IstioFiltersGetter interface {
	IstioFilters(namespace string) IstioFilterInterface
}

// IstioFilterInterface has methods to work with IstioFilter resources.
type IstioFilterInterface interface {
	Create(ctx context.Context, istioFilter *v1alpha1.IstioFilter, opts v1.CreateOptions) (*v1alpha1.IstioFilter, error)
	Update(ctx context.Context, istioFilter *v1alpha1.IstioFilter, opts v1.UpdateOptions) (*v1alpha1.IstioFilter, error)
	UpdateStatus(ctx context.Context, istioFilter *v1alpha1.IstioFilter, opts v1.UpdateOptions) (*v1alpha1.IstioFilter, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.IstioFilter, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.IstioFilterList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IstioFilter, err error)
	IstioFilterExpansion
}

// istioFilters implements IstioFilterInterface
type istioFilters struct {
	client rest.Interface
	ns     string
}

// newIstioFilters returns a IstioFilters
func newIstioFilters(c *IstiofilterV1alpha1Client, namespace string) *istioFilters {
	return &istioFilters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the istioFilter, and returns the corresponding istioFilter object, and an error if there is any.
func (c *istioFilters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IstioFilter, err error) {
	result = &v1alpha1.IstioFilter{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("istiofilters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IstioFilters that match those selectors.
func (c *istioFilters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IstioFilterList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.IstioFilterList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("istiofilters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested istioFilters.
func (c *istioFilters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("istiofilters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a istioFilter and creates it.  Returns the server's representation of the istioFilter, and an error, if there is any.
func (c *istioFilters) Create(ctx context.Context, istioFilter *v1alpha1.IstioFilter, opts v1.CreateOptions) (result *v1alpha1.IstioFilter, err error) {
	result = &v1alpha1.IstioFilter{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("istiofilters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(istioFilter).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a istioFilter and updates it. Returns the server's representation of the istioFilter, and an error, if there is any.
func (c *istioFilters) Update(ctx context.Context, istioFilter *v1alpha1.IstioFilter, opts v1.UpdateOptions) (result *v1alpha1.IstioFilter, err error) {
	result = &v1alpha1.IstioFilter{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("istiofilters").
		Name(istioFilter.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(istioFilter).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *istioFilters) UpdateStatus(ctx context.Context, istioFilter *v1alpha1.IstioFilter, opts v1.UpdateOptions) (result *v1alpha1.IstioFilter, err error) {
	result = &v1alpha1.IstioFilter{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("istiofilters").
		Name(istioFilter.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(istioFilter).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the istioFilter and deletes it. Returns an error if one occurs.
func (c *istioFilters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("istiofilters").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *istioFilters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("istiofilters").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched istioFilter.
func (c *istioFilters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IstioFilter, err error) {
	result = &v1alpha1.IstioFilter{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("istiofilters").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
