// Copyright IstioFilter Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/istio-conductor/istiofilter/client-go/pkg/apis/istiofilter/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIstioFilters implements IstioFilterInterface
type FakeIstioFilters struct {
	Fake *FakeIstiofilterV1alpha1
	ns   string
}

var istiofiltersResource = schema.GroupVersionResource{Group: "istiofilter.istio-conductor.org", Version: "v1alpha1", Resource: "istiofilters"}

var istiofiltersKind = schema.GroupVersionKind{Group: "istiofilter.istio-conductor.org", Version: "v1alpha1", Kind: "IstioFilter"}

// Get takes name of the istioFilter, and returns the corresponding istioFilter object, and an error if there is any.
func (c *FakeIstioFilters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IstioFilter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(istiofiltersResource, c.ns, name), &v1alpha1.IstioFilter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IstioFilter), err
}

// List takes label and field selectors, and returns the list of IstioFilters that match those selectors.
func (c *FakeIstioFilters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IstioFilterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(istiofiltersResource, istiofiltersKind, c.ns, opts), &v1alpha1.IstioFilterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IstioFilterList{ListMeta: obj.(*v1alpha1.IstioFilterList).ListMeta}
	for _, item := range obj.(*v1alpha1.IstioFilterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested istioFilters.
func (c *FakeIstioFilters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(istiofiltersResource, c.ns, opts))

}

// Create takes the representation of a istioFilter and creates it.  Returns the server's representation of the istioFilter, and an error, if there is any.
func (c *FakeIstioFilters) Create(ctx context.Context, istioFilter *v1alpha1.IstioFilter, opts v1.CreateOptions) (result *v1alpha1.IstioFilter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(istiofiltersResource, c.ns, istioFilter), &v1alpha1.IstioFilter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IstioFilter), err
}

// Update takes the representation of a istioFilter and updates it. Returns the server's representation of the istioFilter, and an error, if there is any.
func (c *FakeIstioFilters) Update(ctx context.Context, istioFilter *v1alpha1.IstioFilter, opts v1.UpdateOptions) (result *v1alpha1.IstioFilter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(istiofiltersResource, c.ns, istioFilter), &v1alpha1.IstioFilter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IstioFilter), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIstioFilters) UpdateStatus(ctx context.Context, istioFilter *v1alpha1.IstioFilter, opts v1.UpdateOptions) (*v1alpha1.IstioFilter, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(istiofiltersResource, "status", c.ns, istioFilter), &v1alpha1.IstioFilter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IstioFilter), err
}

// Delete takes name of the istioFilter and deletes it. Returns an error if one occurs.
func (c *FakeIstioFilters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(istiofiltersResource, c.ns, name), &v1alpha1.IstioFilter{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIstioFilters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(istiofiltersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.IstioFilterList{})
	return err
}

// Patch applies the patch and returns the patched istioFilter.
func (c *FakeIstioFilters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IstioFilter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(istiofiltersResource, c.ns, name, pt, data, subresources...), &v1alpha1.IstioFilter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IstioFilter), err
}
