// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/v1alpha1/istiofilter.proto

// `IstioFilter` defines filters that apply to istio configuration.

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// DeepCopyInto supports using IstioFilter within kubernetes types, where deepcopy-gen is used.
func (in *IstioFilter) DeepCopyInto(out *IstioFilter) {
	p := proto.Clone(in).(*IstioFilter)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioFilter. Required by controller-gen.
func (in *IstioFilter) DeepCopy() *IstioFilter {
	if in == nil {
		return nil
	}
	out := new(IstioFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new IstioFilter. Required by controller-gen.
func (in *IstioFilter) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using IstioFilter_Selector within kubernetes types, where deepcopy-gen is used.
func (in *IstioFilter_Selector) DeepCopyInto(out *IstioFilter_Selector) {
	p := proto.Clone(in).(*IstioFilter_Selector)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioFilter_Selector. Required by controller-gen.
func (in *IstioFilter_Selector) DeepCopy() *IstioFilter_Selector {
	if in == nil {
		return nil
	}
	out := new(IstioFilter_Selector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new IstioFilter_Selector. Required by controller-gen.
func (in *IstioFilter_Selector) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using IstioFilter_Change within kubernetes types, where deepcopy-gen is used.
func (in *IstioFilter_Change) DeepCopyInto(out *IstioFilter_Change) {
	p := proto.Clone(in).(*IstioFilter_Change)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioFilter_Change. Required by controller-gen.
func (in *IstioFilter_Change) DeepCopy() *IstioFilter_Change {
	if in == nil {
		return nil
	}
	out := new(IstioFilter_Change)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new IstioFilter_Change. Required by controller-gen.
func (in *IstioFilter_Change) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using IstioFilter_StringMatch within kubernetes types, where deepcopy-gen is used.
func (in *IstioFilter_StringMatch) DeepCopyInto(out *IstioFilter_StringMatch) {
	p := proto.Clone(in).(*IstioFilter_StringMatch)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioFilter_StringMatch. Required by controller-gen.
func (in *IstioFilter_StringMatch) DeepCopy() *IstioFilter_StringMatch {
	if in == nil {
		return nil
	}
	out := new(IstioFilter_StringMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new IstioFilter_StringMatch. Required by controller-gen.
func (in *IstioFilter_StringMatch) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using IstioFilter_Match within kubernetes types, where deepcopy-gen is used.
func (in *IstioFilter_Match) DeepCopyInto(out *IstioFilter_Match) {
	p := proto.Clone(in).(*IstioFilter_Match)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioFilter_Match. Required by controller-gen.
func (in *IstioFilter_Match) DeepCopy() *IstioFilter_Match {
	if in == nil {
		return nil
	}
	out := new(IstioFilter_Match)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new IstioFilter_Match. Required by controller-gen.
func (in *IstioFilter_Match) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using IstioFilter_SelectorMatch within kubernetes types, where deepcopy-gen is used.
func (in *IstioFilter_SelectorMatch) DeepCopyInto(out *IstioFilter_SelectorMatch) {
	p := proto.Clone(in).(*IstioFilter_SelectorMatch)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioFilter_SelectorMatch. Required by controller-gen.
func (in *IstioFilter_SelectorMatch) DeepCopy() *IstioFilter_SelectorMatch {
	if in == nil {
		return nil
	}
	out := new(IstioFilter_SelectorMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new IstioFilter_SelectorMatch. Required by controller-gen.
func (in *IstioFilter_SelectorMatch) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using IstioFilter_Patch within kubernetes types, where deepcopy-gen is used.
func (in *IstioFilter_Patch) DeepCopyInto(out *IstioFilter_Patch) {
	p := proto.Clone(in).(*IstioFilter_Patch)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioFilter_Patch. Required by controller-gen.
func (in *IstioFilter_Patch) DeepCopy() *IstioFilter_Patch {
	if in == nil {
		return nil
	}
	out := new(IstioFilter_Patch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new IstioFilter_Patch. Required by controller-gen.
func (in *IstioFilter_Patch) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
