// Copyright IstioFilter Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	configurationv1alpha1 "github.com/istio-conductor/istiofilter/client-go/pkg/apis/configuration/v1alpha1"
	versioned "github.com/istio-conductor/istiofilter/client-go/pkg/clientset/versioned"
	internalinterfaces "github.com/istio-conductor/istiofilter/client-go/pkg/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/istio-conductor/istiofilter/client-go/pkg/listers/configuration/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// IstioFilterInformer provides access to a shared informer and lister for
// IstioFilters.
type IstioFilterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.IstioFilterLister
}

type istioFilterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewIstioFilterInformer constructs a new informer for IstioFilter type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewIstioFilterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredIstioFilterInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredIstioFilterInformer constructs a new informer for IstioFilter type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredIstioFilterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ConfigurationV1alpha1().IstioFilters(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ConfigurationV1alpha1().IstioFilters(namespace).Watch(context.TODO(), options)
			},
		},
		&configurationv1alpha1.IstioFilter{},
		resyncPeriod,
		indexers,
	)
}

func (f *istioFilterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredIstioFilterInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *istioFilterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&configurationv1alpha1.IstioFilter{}, f.defaultInformer)
}

func (f *istioFilterInformer) Lister() v1alpha1.IstioFilterLister {
	return v1alpha1.NewIstioFilterLister(f.Informer().GetIndexer())
}
