/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kubetype-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/istio-conductor/istiofilter/api/v1alpha1"
	metav1alpha1 "istio.io/api/meta/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

//
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// IstioFilter defines filters that apply to istio configuration.
//
// <!-- crd generation tags
// +cue-gen:IstioFilter:groupName:istio-conductor.org
// +cue-gen:IstioFilter:version:v1alpha1
// +cue-gen:IstioFilter:storageVersion
// +cue-gen:IstioFilter:subresource:status
// +cue-gen:IstioFilter:scope:Namespaced
// +cue-gen:IstioFilter:resource:categories=istio-conductor-org,shortNames=if
// +cue-gen:IstioFilter:printerColumn:name=Schema,type=string,JSONPath=.spec.schema,description="Istio Filter kind"
// +cue-gen:IstioFilter:printerColumn:name=Age,type=date,JSONPath=.metadata.creationTimestamp,description="CreationTimestamp is a timestamp
// representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations.
// Clients may not set this value. It is represented in RFC3339 form and is in UTC.
// Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata"
// +cue-gen:IstioFilter:preserveUnknownFields:true
// -->
//
// <!-- go code generation tags
// +kubetype-gen
// +kubetype-gen:groupVersion=istio-conductor.org/v1alpha1
// +genclient
// +k8s:deepcopy-gen=true
// -->
type IstioFilter struct {
	v1.TypeMeta `json:",inline"`
	// +optional
	v1.ObjectMeta `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`

	// Spec defines the implementation of this definition.
	// +optional
	Spec apiv1alpha1.IstioFilter `json:"spec,omitempty" protobuf:"bytes,2,opt,name=spec"`

	Status metav1alpha1.IstioStatus `json:"status"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// IstioFilterList is a collection of IstioFilters.
type IstioFilterList struct {
	v1.TypeMeta `json:",inline"`
	// +optional
	v1.ListMeta `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`
	Items       []IstioFilter `json:"items" protobuf:"bytes,2,rep,name=items"`
}
