apiVersion: v1
kind: ServiceAccount
metadata:
  name: istiofilter
  namespace: istio-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: istiofilter
  namespace: istio-system
  name: istiofilter
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - events
    verbs:
      - '*'
  - verbs:
      - '*'
    apiGroups:
      - coordination.k8s.io
    resources:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: istiofilter
  namespace: istio-system
  name: istiofilter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: istiofilter
subjects:
  - kind: ServiceAccount
    name: istiofilter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: istiofilter
  name: istiofilter-istio-system
rules:
  - apiGroups:
      - networking.istio.io
    resources:
      - '*'
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - configuration.istio-conductor.org/v1alpha1
    resources:
      - '*'
    verbs:
      - get
      - watch
      - list
      - update
      - patch
      - create
      - delete
  - apiGroups:
      - networking.istio.io
    resources:
      - virtualservices
      - destinationrules
    verbs:
      - get
      - watch
      - list
      - update
      - patch
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: istiofilter
  name: istiofilter-istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istiofilter-istio-system
subjects:
  - kind: ServiceAccount
    name: istiofilter
    namespace: istio-system
---
apiVersion: v1
data:
  key.pem: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQ3NYZ1dWNm50NVV1c1cKZEJvdlEzKzB6RW41UG9SVW02NSt5cTFxSzBjTU5sZGEzZ1BQNTVlSS9RblBIZzBSOUNlTmJoZm5IUXNkQ0hIMwpPNTdSeUZSbzk1Qm1CS0FERERPSy82OHVpTnJOYm1XWnl5dHVzckJVQ3BzQ3kyY1dyM3puTGVEZFREZGl1bWZjCkJEYklzZnhxcEpQSXVsc0ZBbVFRQ0M3cHZybndiWS9WWjR5MEpocUpOM0tlRWFjbmQvb0psckZzc1VpTUFkUUMKYW90SXQwSU9GUnpOYUoxbkdUUTJ3NVhDdDFPeTYvbXZWNGF1a002VXdwT3dGaUxCbWFwQm1DMHdKSDRLZmo3YQoyTnN0d0lTelpWTSt6ODdTeXBGck9KMUtnOGpWZ1RGeVRESnFkUU9KRWhXZ3FoZXJTMTA0UmlQS1F1SktPNDRWCmwrSjdaOU5MQWdNQkFBRUNnZ0VBWFh2QTI4WUlvWXh2SkFaa0RTNDJuUUFQUHJiQlhvSHc2YU5TMmpvT2xua0MKZDYzaHMyaVByeVJOcFo5T3gyWDc3YURBSmdDQ2ZvU09DdUN6Q21QMEk5bmczdk96TlBQeElIbjdzT2xZZ2dKVgo2RXRnaXZFdTRPVy9uSXhrcE5FWWxPazFBOURLV1Nsd0dzdk9TcHI5bzNrUERkYkVkcnNOT2dTMkxOL2NTS0MvCmZiQnhLQlpYY0lOZTVBakMycExDSDJwK2ZabWJtYjN0YlBNODFBN012dWJsZ2dTOWFvdGlHaEhCdzI0WlRBUUIKbEkxZXdPVzdPVFU1cmxTQW45SUtZUlRZdnNKQWhrR0M4V2Q3Und4TXdMS2NuWDZMVWtiSDYwRmR4OXQxMkoyRgpEM0NQOW1oUXVtLzc3M2JmSFJaN0EzWUQzVE9LSkVCYm5nTjN0bm95QVFLQmdRRFMwMERWUmJ6eGdGNldnSGNYCk11ZUY1Q1JRdjA2RGVkSnVZQVBRUDQ0M2RhMGtlUHd5WmYrNUxXVks0WG56K0VjMy80TUs1SjJFYUFjYmRRN1oKV1RJMUtDaWp2NWtwOE5MTHphN0ZUemlRUXJIQi9EbE9CM0lmaDlEODdrd2YyK2VuUnlEd0ZJYUp3dFFPMmVMRgpiWEpYUVVIclYrN1BtK0c4b2ljbTNyR1Y0UUtCZ1FEUlRTdmFXQ3h1L2UvYW56RFhDR2I5OUdGSHE0cVRZU3RlCnBFeEZVMmVjQ3FOSkdzbmhMM29TNFZwbmlWOUcvdE54OEVGYjhDMUlPU3k2TGF5TGR5S2xFc0hySXBDRTlSRXkKQ1ZnV3pUK2RzQ1RzUFVPa09WTVNEYjdMeThJaVorcFdnYXY3MFZsT21SOG5rTVVHMlFoRkdkNVA3bzhGaTZWNAo5ZGFQd0JOMnF3S0JnRzZUeXgrUnNtWmcxRHZRS2FhTFZwQU5kMWE2NEsxcENneEdZL21vUENtdW1SL1dMVUVwCjZwVHYwSDhVQUdrTVFoNkc3KzZZdGwycVNvQUdSOEdNWFI4d2J4QmtBQ3ZWV2xyM0NNSUlxVHhSSHZjR0dmQnAKUzF4cVdoMHZ4OUcxLzZ6blM4bGdtcWhLL2ZyRUlZTTN3bzh0ZFN2Qk5VckRFZ1ZrYjNDZHdUdEJBb0dCQUtwUgpGQWhmaS9qZDUxcU9CQjVYbGdlOTM1T0V3Z1ZnSXZ5bTBmSHdCdlh4cWlJSkRKS1VJZEJQVlZPL2M2ckFIcXd2CkIrQ2F0eDU0ZUM4Z2o3SUZ4a2x4MUI5VlJ5a0tpMjJlTVBLTkh1Rmd2d3NHWjQ2eG55bW55Y1RwRUJjVFhKdjgKZFVrN2VHTC9NMXpzNzRlOUFIL0tweCtBVHg0Q0h5c3BVZW8wTVNKMUFvR0FMeHg1bUZCckdaemRCZ1l0eWVGdgpCRE1iSklkU2QyNUhtYzJ1MzQyaDh3NERSRHd3Mk05WUJMaEJVQlpvM210QWI0NHgzNlZRdjRoMFp6cnJzT1lQClNndUtna2hCaDRUWFRqY3F3ZTcwRFpvV2ZsYVNWWko0TjJadUMvcks3VkVEQ2Yvb0g1Sk8rbG9MRU9wWlk4Z3IKbUpLejdZYnZIanY5TVFhb0ZCWUtVVFE9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
  cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVGakNDQXY2Z0F3SUJBZ0lVUDhBTDl4ODdJbzFjTHB2N1IvSWpmaHZ2dDlzd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dZUXhDekFKQmdOVkJBWVRBa05PTVJBd0RnWURWUVFJREFkQ1pXbHFhVzVuTVJBd0RnWURWUVFIREFkQwpaV2xxYVc1bk1Sd3dHZ1lEVlFRS0RCTnBjM1JwYnkxamIyNWtkV04wYjNJdWIzSm5NUXd3Q2dZRFZRUUxEQU5QCmNtY3hKVEFqQmdOVkJBTU1IR2x6ZEdsdlptbHNkR1Z5TG1semRHbHZMWE41YzNSbGJTNXpkbU13SUJjTk1qRXcKTWpBM01EZ3lOalV4V2hnUE1qRXlNVEF4TVRRd09ESTJOVEZhTUlHRU1Rc3dDUVlEVlFRR0V3SkRUakVRTUE0RwpBMVVFQ0F3SFFtVnBhbWx1WnpFUU1BNEdBMVVFQnd3SFFtVnBhbWx1WnpFY01Cb0dBMVVFQ2d3VGFYTjBhVzh0ClkyOXVaSFZqZEc5eUxtOXlaekVNTUFvR0ExVUVDd3dEVDNKbk1TVXdJd1lEVlFRRERCeHBjM1JwYjJacGJIUmwKY2k1cGMzUnBieTF6ZVhOMFpXMHVjM1pqTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQwpBUUVBckY0RmxlcDdlVkxyRm5RYUwwTi90TXhKK1Q2RVZKdXVmc3F0YWl0SEREWlhXdDREeitlWGlQMEp6eDROCkVmUW5qVzRYNXgwTEhRaHg5enVlMGNoVWFQZVFaZ1NnQXd3eml2K3ZMb2phelc1bG1jc3Jickt3VkFxYkFzdG4KRnE5ODV5M2czVXczWXJwbjNBUTJ5TEg4YXFTVHlMcGJCUUprRUFndTZiNjU4RzJQMVdlTXRDWWFpVGR5bmhHbgpKM2Y2Q1pheGJMRklqQUhVQW1xTFNMZENEaFVjeldpZFp4azBOc09Wd3JkVHN1djVyMWVHcnBET2xNS1RzQllpCndabXFRWmd0TUNSK0NuNCsydGpiTGNDRXMyVlRQcy9PMHNxUmF6aWRTb1BJMVlFeGNrd3lhblVEaVJJVm9Lb1gKcTB0ZE9FWWp5a0xpU2p1T0ZaZmllMmZUU3dJREFRQUJvM3d3ZWpBZEJnTlZIUTRFRmdRVTd3Q1JBbjdQVVE0VwpJMDFYRlBIN3h0NG1XTTh3SHdZRFZSMGpCQmd3Rm9BVTd3Q1JBbjdQVVE0V0kwMVhGUEg3eHQ0bVdNOHdEd1lEClZSMFRBUUgvQkFVd0F3RUIvekFuQmdOVkhSRUVJREFlZ2h4cGMzUnBiMlpwYkhSbGNpNXBjM1JwYnkxemVYTjAKWlcwdWMzWmpNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUE2QkVjbUF3RFZpdkU1OE1iajV3d1doNmtvWWtqdQpGL3dYTE1GSlZYbXViVDNlaUJ1TnM2OWlBZHdrSmxMVUkzNitYZExSSDFEUEh3QzBEK0VyYkZIMisyTGREZUYxCmJ2aHI2NzhPM1UxdGpsVjJab2hJWVc4a1hlVHQzUzZKcHEwMVkzUmk5Mi8vc3BXVEkvNjlGSmFZNmRHaTJ2M1IKQ2tGTDB3U2N2eGpId2tjS1lIbWZCR2ZDb3pQVHQ3TFp4TjVLLzFldFpYUzFZUmlJcEcrcTNXd1pBeEJXZ1lkaQpHRHhGV0J0RHZCMkdUUDVORWcrdGczZloyRndKK01QRDg2YThtTXBQcEdRYVJ4SS9NaWRDZVJMaUZFUnMzNWMyCmhRSUZFYWxpaE5pWHFoN3lFUFhnLzl0c0J3UmlhZzc1dzcwMVJPVHdLTzlNa21MaWcxcTNSM3F1Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
kind: Secret
metadata:
  name: "istiofilter-certs"
  namespace: istio-system
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "istiofilter"
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: "istiofilter"
  template:
    metadata:
      labels:
        app: "istiofilter"
    spec:
      serviceAccountName: istiofilter
      volumes:
        - name: cert
          secret:
            secretName: "istiofilter-certs"
      containers:
        - name: "istiofilter"
          image: istioconductor/istiofilter:latest
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: /root/cert
              name: cert
          args:
            - --privilegeNamespaces=istio-system
            - --port=443
            - --keyFile=/root/cert/key.pem
            - --certFile=/root/cert/cert.pem
            - --logLevel=debug
---
apiVersion: v1
kind: Service
metadata:
  namespace: istio-system
  name: istiofilter
spec:
  selector:
    app: "istiofilter"
  ports:
    - port: 443
      targetPort: 443
      name: https
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: istiofilter-webhook
webhooks:
  - admissionReviewVersions:
      - v1beta1
      - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVGakNDQXY2Z0F3SUJBZ0lVUDhBTDl4ODdJbzFjTHB2N1IvSWpmaHZ2dDlzd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dZUXhDekFKQmdOVkJBWVRBa05PTVJBd0RnWURWUVFJREFkQ1pXbHFhVzVuTVJBd0RnWURWUVFIREFkQwpaV2xxYVc1bk1Sd3dHZ1lEVlFRS0RCTnBjM1JwYnkxamIyNWtkV04wYjNJdWIzSm5NUXd3Q2dZRFZRUUxEQU5QCmNtY3hKVEFqQmdOVkJBTU1IR2x6ZEdsdlptbHNkR1Z5TG1semRHbHZMWE41YzNSbGJTNXpkbU13SUJjTk1qRXcKTWpBM01EZ3lOalV4V2hnUE1qRXlNVEF4TVRRd09ESTJOVEZhTUlHRU1Rc3dDUVlEVlFRR0V3SkRUakVRTUE0RwpBMVVFQ0F3SFFtVnBhbWx1WnpFUU1BNEdBMVVFQnd3SFFtVnBhbWx1WnpFY01Cb0dBMVVFQ2d3VGFYTjBhVzh0ClkyOXVaSFZqZEc5eUxtOXlaekVNTUFvR0ExVUVDd3dEVDNKbk1TVXdJd1lEVlFRRERCeHBjM1JwYjJacGJIUmwKY2k1cGMzUnBieTF6ZVhOMFpXMHVjM1pqTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQwpBUUVBckY0RmxlcDdlVkxyRm5RYUwwTi90TXhKK1Q2RVZKdXVmc3F0YWl0SEREWlhXdDREeitlWGlQMEp6eDROCkVmUW5qVzRYNXgwTEhRaHg5enVlMGNoVWFQZVFaZ1NnQXd3eml2K3ZMb2phelc1bG1jc3Jickt3VkFxYkFzdG4KRnE5ODV5M2czVXczWXJwbjNBUTJ5TEg4YXFTVHlMcGJCUUprRUFndTZiNjU4RzJQMVdlTXRDWWFpVGR5bmhHbgpKM2Y2Q1pheGJMRklqQUhVQW1xTFNMZENEaFVjeldpZFp4azBOc09Wd3JkVHN1djVyMWVHcnBET2xNS1RzQllpCndabXFRWmd0TUNSK0NuNCsydGpiTGNDRXMyVlRQcy9PMHNxUmF6aWRTb1BJMVlFeGNrd3lhblVEaVJJVm9Lb1gKcTB0ZE9FWWp5a0xpU2p1T0ZaZmllMmZUU3dJREFRQUJvM3d3ZWpBZEJnTlZIUTRFRmdRVTd3Q1JBbjdQVVE0VwpJMDFYRlBIN3h0NG1XTTh3SHdZRFZSMGpCQmd3Rm9BVTd3Q1JBbjdQVVE0V0kwMVhGUEg3eHQ0bVdNOHdEd1lEClZSMFRBUUgvQkFVd0F3RUIvekFuQmdOVkhSRUVJREFlZ2h4cGMzUnBiMlpwYkhSbGNpNXBjM1JwYnkxemVYTjAKWlcwdWMzWmpNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUE2QkVjbUF3RFZpdkU1OE1iajV3d1doNmtvWWtqdQpGL3dYTE1GSlZYbXViVDNlaUJ1TnM2OWlBZHdrSmxMVUkzNitYZExSSDFEUEh3QzBEK0VyYkZIMisyTGREZUYxCmJ2aHI2NzhPM1UxdGpsVjJab2hJWVc4a1hlVHQzUzZKcHEwMVkzUmk5Mi8vc3BXVEkvNjlGSmFZNmRHaTJ2M1IKQ2tGTDB3U2N2eGpId2tjS1lIbWZCR2ZDb3pQVHQ3TFp4TjVLLzFldFpYUzFZUmlJcEcrcTNXd1pBeEJXZ1lkaQpHRHhGV0J0RHZCMkdUUDVORWcrdGczZloyRndKK01QRDg2YThtTXBQcEdRYVJ4SS9NaWRDZVJMaUZFUnMzNWMyCmhRSUZFYWxpaE5pWHFoN3lFUFhnLzl0c0J3UmlhZzc1dzcwMVJPVHdLTzlNa21MaWcxcTNSM3F1Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: istiofilter
        namespace: istio-system
        path: /mutate
        port: 443
    failurePolicy: Fail
    matchPolicy: Exact
    name: istiofilter.istio-system.svc.cluster.local
    reinvocationPolicy: Never
    rules:
      - apiGroups:
          - "networking.istio.io"
        apiVersions:
          - v1alpha3
        operations:
          - CREATE
          - UPDATE
        resources:
          - virtualservices
          - destinationrules
        scope: '*'
    sideEffects: None
    timeoutSeconds: 30